version: '2'
services:
    myson-app:
        image: myson
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://myson-mysql:3306/myson?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=myson-elasticsearch:9300
        ports:
            - 8080:8080
    myson-mysql:
        extends:
            file: mysql.yml
            service: myson-mysql
    myson-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: myson-elasticsearch
